# Generated by Django 4.1.3 on 2023-03-04 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_nom', models.CharField(blank=True, max_length=128, null=True)),
                ('m_description', models.TextField(blank=True, null=True)),
                ('m_elt_tables', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_title', models.CharField(blank=True, max_length=128, null=True)),
                ('m_date_posted', models.DateTimeField(blank=True, null=True)),
                ('m_cover_picture', models.FileField(blank=True, null=True, upload_to='')),
                ('m_template', models.TextField(blank=True, null=True)),
                ('m_author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
