# Generated by Django 4.1.3 on 2023-03-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_nom', models.CharField(blank=True, max_length=128, null=True)),
                ('m_description', models.TextField(blank=True, null=True)),
                ('m_mode_de_transmission', models.TextField(blank=True, null=True)),
                ('m_signes_et_symptomes', models.TextField(blank=True, null=True)),
                ('m_manifeste', models.TextField(blank=True, null=True)),
                ('m_complications', models.TextField(blank=True, null=True)),
                ('m_traitement', models.TextField(blank=True, null=True)),
                ('m_prevention', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
