# Generated by Django 4.1.3 on 2023-03-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_maladie_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_phone', models.TextField(blank=True, null=True)),
                ('m_mail', models.TextField(blank=True, null=True)),
                ('m_networks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_logo', models.FileField(blank=True, null=True, upload_to='')),
                ('m_nom', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
