# Generated by Django 4.2.1 on 2023-05-31 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_logo', models.FileField(blank=True, null=True, upload_to='')),
                ('m_name', models.CharField(blank=True, max_length=64, null=True)),
                ('m_fields_type', models.TextField(blank=True, null=True)),
                ('m_fields', models.TextField(blank=True, null=True)),
                ('m_description', models.TextField(blank=True, null=True)),
                ('m_domain_type', models.CharField(blank=True, default='Aggregate', max_length=64, null=True)),
                ('m_value_type', models.CharField(blank=True, default='Number', max_length=64, null=True)),
                ('m_aggregation_type', models.CharField(blank=True, default='A', max_length=64, null=True)),
                ('is_zero_collect', models.BooleanField(blank=True, null=True)),
                ('m_default_value', models.IntegerField(blank=True, null=True)),
                ('is_constant', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ('m_name',),
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(blank=True, max_length=64, null=True)),
                ('m_periode', models.CharField(blank=True, max_length=64, null=True)),
                ('m_sub_periode', models.CharField(blank=True, max_length=64, null=True)),
                ('m_formulaire', models.TextField(blank=True, null=True)),
                ('m_start_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('m_dataelements', models.ManyToManyField(null=True, to='ctn_bpf.dataelement')),
            ],
            options={
                'ordering': ('-m_start_date',),
            },
        ),
        migrations.CreateModel(
            name='DataSetValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date_creation', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('m_period_value', models.CharField(blank=True, max_length=128, null=True)),
                ('m_sub_period_value', models.CharField(blank=True, max_length=128, null=True)),
                ('m_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.dataset')),
            ],
            options={
                'ordering': ('-m_date_creation',),
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_nom', models.CharField(blank=True, max_length=256, null=True)),
                ('m_date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('m_date_modif', models.DateTimeField(auto_now=True)),
                ('m_value_fields', models.TextField(blank=True, null=True)),
                ('is_rapported', models.BooleanField(blank=True, default=False, null=True)),
                ('m_reported_fields', models.TextField(blank=True, null=True)),
                ('m_pic_represented', models.FileField(blank=True, null=True, upload_to='')),
                ('m_indicateurs_reels', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('m_type_entity', 'm_value_fields'),
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_nom', models.CharField(blank=True, max_length=128, null=True)),
                ('m_date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('m_date_modif', models.DateTimeField(auto_now=True)),
                ('m_fields', models.TextField(blank=True, default='', null=True)),
                ('m_type_fields', models.TextField(blank=True, default='', null=True)),
                ('m_fields_rapported', models.TextField(blank=True, default='', null=True)),
                ('m_type_fields_rapp', models.TextField(blank=True, default='', null=True)),
                ('m_fields_calculate', models.TextField(blank=True, default='', null=True)),
                ('m_fields_fonction_calculate', models.TextField(blank=True, default='', null=True)),
                ('m_enum_values', models.TextField(blank=True, default='', null=True)),
                ('is_pic_represented', models.BooleanField(blank=True, default=False, null=True)),
                ('is_tache', models.BooleanField(blank=True, default=False, null=True)),
                ('indicateur_fields', models.TextField(blank=True, default='', null=True)),
                ('m_indicateurs_values', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=128)),
                ('m_periodicite', models.TextField(blank=True, null=True)),
                ('m_sub_periodicite', models.TextField(blank=True, null=True)),
                ('m_final_cible', models.TextField(blank=True, null=True)),
                ('m_cibles', models.TextField(blank=True, null=True)),
                ('m_sources_data', models.TextField(blank=True, null=True)),
                ('m_data_verification', models.TextField(blank=True, null=True)),
                ('m_objectif_indi', models.TextField(blank=True, null=True)),
                ('m_verification_indi', models.CharField(blank=True, max_length=128, null=True)),
                ('m_colors_code', models.CharField(blank=True, max_length=128, null=True)),
                ('m_alerts_code', models.CharField(blank=True, max_length=128, null=True)),
                ('m_others', models.TextField(blank=True, null=True)),
                ('m_numerateur', models.CharField(blank=True, max_length=128, null=True)),
                ('m_denominateur', models.CharField(blank=True, max_length=128, null=True)),
                ('m_unite', models.CharField(blank=True, default='%', max_length=32, null=True)),
                ('m_coefficient', models.IntegerField(blank=True, null=True)),
                ('m_fields', models.TextField(blank=True, null=True)),
                ('m_values', models.TextField(blank=True, null=True)),
                ('m_datalets_calcul', models.CharField(blank=True, max_length=128, null=True)),
                ('m_start_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('m_secundo_options', models.TextField(blank=True, null=True)),
                ('m_enti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.entity')),
            ],
            options={
                'ordering': ('-m_start_date',),
            },
        ),
        migrations.CreateModel(
            name='IndicateurPeriode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_periode', models.CharField(blank=True, max_length=128, null=True)),
                ('m_sub_periode', models.CharField(blank=True, max_length=128, null=True)),
                ('m_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicateurVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_periode', models.CharField(blank=True, max_length=128, null=True)),
                ('m_date_created', models.DateTimeField(auto_now=True, null=True)),
                ('m_indicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.indicateur')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(blank=True, max_length=32, null=True)),
                ('nom', models.CharField(max_length=128)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('purpose', models.TextField(blank=True, null=True)),
                ('structures_roles', models.TextField(default='Responsible|Accountable|Consulted|Informed')),
                ('default_options', models.BooleanField(blank=True, default=True, null=True)),
                ('finan_options', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('default_struc_name', models.CharField(blank=True, default='Structure', max_length=128, null=True)),
                ('repeat_mode', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'ordering': ('nom', 'sigle'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_content', models.TextField(blank=True, null=True)),
                ('m_date_send', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperaApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_picture', models.FileField(blank=True, null=True, upload_to='')),
                ('m_name', models.CharField(blank=True, max_length=64, null=True)),
                ('m_description', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(blank=True, default=False, null=True)),
                ('m_website', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('nom', models.CharField(blank=True, max_length=256, null=True)),
                ('resultat_attendu', models.TextField(blank=True, null=True)),
                ('etat', models.CharField(default='0', max_length=32)),
                ('notification', models.CharField(blank=True, max_length=128, null=True)),
                ('semaines', models.CharField(blank=True, max_length=128, null=True)),
                ('date_creation', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('m_tache_plannification', models.CharField(blank=True, max_length=64, null=True)),
                ('montant', models.FloatField(blank=True, default=0, null=True)),
                ('montant2', models.FloatField(blank=True, default=0, null=True)),
                ('priorite', models.CharField(blank=True, max_length=64, null=True)),
                ('m_value', models.TextField(blank=True, default='', null=True)),
                ('m_value_reported', models.TextField(blank=True, default='', null=True)),
                ('is_RACI', models.IntegerField(blank=True, default=0, null=True)),
                ('m_commentaire', models.TextField(blank=True, default='', null=True)),
                ('date_rapported', models.DateTimeField(blank=True, null=True)),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ('nom', 'date_creation'),
            },
        ),
        migrations.CreateModel(
            name='OperationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_value_reported', models.TextField(blank=True, null=True)),
                ('m_date_realisation', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('m_commentaire', models.TextField(blank=True, null=True)),
                ('etat', models.CharField(default='0', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='OperationRapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='')),
                ('nom_piece_jointe', models.CharField(blank=True, max_length=128, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('type_rapport', models.CharField(blank=True, default='c', max_length=2, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_value', models.CharField(blank=True, max_length=128, null=True)),
                ('m_decoupage', models.TextField(blank=True, null=True)),
                ('m_decoupage_description', models.TextField(blank=True, null=True)),
                ('m_date_creation', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('m_config', models.BooleanField(blank=True, null=True)),
                ('m_initial', models.BooleanField(blank=True, null=True)),
                ('m_logic_type', models.IntegerField(blank=True, null=True)),
                ('m_code_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('m_value',),
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=128, null=True)),
                ('prenom', models.CharField(blank=True, max_length=128, null=True)),
                ('mail', models.CharField(blank=True, max_length=128, null=True)),
                ('tel', models.CharField(blank=True, max_length=128, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('actual_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.institution')),
                ('bd_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Personnel_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_file', models.FileField(blank=True, null=True, upload_to='')),
                ('m_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.IntegerField(blank=True, default=0, null=True)),
                ('m_nature', models.CharField(blank=True, default='0', max_length=2, null=True)),
                ('is_simple_user', models.IntegerField(blank=True, default=0, null=True)),
                ('m_extra_fields', models.TextField(blank=True, default='', null=True)),
                ('m_extra_types', models.TextField(blank=True, default='', null=True)),
                ('actual_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
                ('m_simple_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.entitytype')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('nom', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('values_hierachy', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_picture', models.FileField(blank=True, null=True, upload_to='')),
                ('m_name', models.CharField(blank=True, max_length=64, null=True)),
                ('m_poste', models.CharField(blank=True, max_length=64, null=True)),
                ('m_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ctn_bpf.entity')),
                ('montant', models.FloatField(blank=True, null=True)),
            ],
            bases=('ctn_bpf.entity',),
        ),
        migrations.CreateModel(
            name='SubPeriode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_sub_value', models.CharField(blank=True, max_length=128, null=True)),
                ('m_decoupage', models.TextField(blank=True, null=True)),
                ('m_decoupage_description', models.TextField(blank=True, null=True)),
                ('m_config_type', models.IntegerField(blank=True, null=True)),
                ('m_periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.periode')),
            ],
        ),
        migrations.CreateModel(
            name='StructureRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_role', models.TextField(blank=True, null=True)),
                ('m_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.structure')),
            ],
            options={
                'ordering': ('m_structure',),
            },
        ),
        migrations.CreateModel(
            name='StructureResponsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date_start', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('m_date_end', models.DateTimeField(blank=True, null=True)),
                ('m_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.personnel')),
                ('m_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.structure')),
            ],
            options={
                'ordering': ('m_structure', '-m_date_start'),
            },
        ),
        migrations.CreateModel(
            name='StructureRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_structure1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='struc1', to='ctn_bpf.structure')),
                ('m_structure2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='struc2', to='ctn_bpf.structure')),
            ],
        ),
        migrations.CreateModel(
            name='Structure_Hierachy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_levels_fields', models.TextField()),
                ('m_levels_values', models.TextField()),
                ('m_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
            ],
        ),
        migrations.AddField(
            model_name='structure',
            name='hierachy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.structure_hierachy'),
        ),
        migrations.AddField(
            model_name='structure',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution'),
        ),
        migrations.CreateModel(
            name='PersonnelRACI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_roles', models.TextField(blank=True, null=True)),
                ('m_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.entity')),
                ('m_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel_Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_start_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('m_responsable', models.BooleanField(blank=True, default=False, null=True)),
                ('m_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.personnel')),
                ('m_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.structure')),
            ],
            options={
                'ordering': ('-m_structure__institution', '-m_start_date', 'm_structure'),
            },
        ),
        migrations.CreateModel(
            name='Personnel_Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_start_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('m_extra_values', models.TextField(blank=True, null=True)),
                ('m_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.entity')),
                ('m_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
                ('m_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.personnel')),
                ('m_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.role')),
            ],
            options={
                'ordering': ('-m_start_date',),
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_code', models.CharField(blank=True, max_length=128, null=True)),
                ('m_bought', models.BooleanField(blank=True, default=False, null=True)),
                ('m_type', models.IntegerField(blank=True, default=1, null=True)),
                ('m_mail_notified', models.BooleanField(blank=True, default=False, null=True)),
                ('m_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(blank=True, max_length=128, null=True)),
                ('m_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.operation')),
                ('m_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='OperationRapport_Eval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('m_status', models.IntegerField(blank=True, default=0, null=True)),
                ('operation_rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.operationrapport')),
            ],
        ),
        migrations.CreateModel(
            name='OperationPeriode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_desc_realisation', models.TextField(blank=True, null=True)),
                ('m_chronogramme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.subperiode')),
                ('m_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.operation')),
            ],
        ),
        migrations.CreateModel(
            name='OperationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_field', models.CharField(blank=True, max_length=32, null=True)),
                ('m_file', models.FileField(blank=True, null=True, upload_to='')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.operation')),
            ],
        ),
        migrations.CreateModel(
            name='OperationEval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('m_status', models.IntegerField(blank=True, default=0, null=True)),
                ('m_values', models.TextField(blank=True, null=True)),
                ('operation_rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.operation')),
            ],
        ),
        migrations.CreateModel(
            name='OperationDetailsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_field', models.CharField(blank=True, max_length=32, null=True)),
                ('m_file', models.FileField(blank=True, null=True, upload_to='')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.operationdetails')),
            ],
        ),
        migrations.AddField(
            model_name='operationdetails',
            name='accountable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountable_2', to='ctn_bpf.personnel'),
        ),
        migrations.AddField(
            model_name='operationdetails',
            name='consulted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulted_2', to='ctn_bpf.personnel'),
        ),
        migrations.AddField(
            model_name='operationdetails',
            name='informed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informed_2', to='ctn_bpf.personnel'),
        ),
        migrations.AddField(
            model_name='operationdetails',
            name='m_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.operation'),
        ),
        migrations.AddField(
            model_name='operationdetails',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.personnel'),
        ),
        migrations.CreateModel(
            name='OperationConsulted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_stars', models.IntegerField(blank=True, null=True)),
                ('m_observations', models.TextField(blank=True, null=True)),
                ('m_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.operation')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='accountable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountable', to='ctn_bpf.personnel'),
        ),
        migrations.AddField(
            model_name='operation',
            name='consulted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulted', to='ctn_bpf.personnel'),
        ),
        migrations.AddField(
            model_name='operation',
            name='informed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informed', to='ctn_bpf.personnel'),
        ),
        migrations.AddField(
            model_name='operation',
            name='m_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.institution'),
        ),
        migrations.AddField(
            model_name='operation',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.personnel'),
        ),
        migrations.CreateModel(
            name='OperaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(blank=True, max_length=128, null=True)),
                ('m_file', models.FileField(blank=True, null=True, upload_to='')),
                ('m_category', models.CharField(blank=True, max_length=128, null=True)),
                ('m_date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('m_description', models.TextField(blank=True, null=True)),
                ('is_public', models.IntegerField(blank=True, null=True)),
                ('m_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
            ],
            options={
                'ordering': ('-m_date_creation',),
            },
        ),
        migrations.CreateModel(
            name='MessageDestinators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_destinators', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.personnel')),
                ('m_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='m_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.personnel'),
        ),
        migrations.CreateModel(
            name='InstitutionDecoupage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_decoupage', models.TextField(blank=True, null=True)),
                ('all_selected', models.BooleanField(blank=True, default=True, null=True)),
                ('m_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
                ('m_periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.periode')),
            ],
        ),
        migrations.CreateModel(
            name='Institution_Periodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_default', models.BooleanField(blank=True, default=False, null=True)),
                ('m_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
                ('m_periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.periode')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='default_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.periode'),
        ),
        migrations.AddField(
            model_name='institution',
            name='default_subperiod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.subperiode'),
        ),
        migrations.AddField(
            model_name='institution',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.owner'),
        ),
        migrations.CreateModel(
            name='InsitutionEntities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_hierachie', models.IntegerField(blank=True, null=True)),
                ('m_entity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.entitytype')),
                ('m_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
            ],
            options={
                'ordering': ('m_institution', 'm_hierachie'),
            },
        ),
        migrations.CreateModel(
            name='IndicateurValElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_valeur', models.CharField(blank=True, max_length=128, null=True)),
                ('m_data_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.dataelement')),
                ('m_indicateurval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.indicateurval')),
            ],
        ),
        migrations.AddField(
            model_name='indicateurval',
            name='m_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.personnel'),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='m_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution'),
        ),
        migrations.CreateModel(
            name='HistoricRACI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_role', models.CharField(blank=True, max_length=3, null=True)),
                ('m_commentaire', models.TextField(blank=True, null=True)),
                ('m_date_realisation', models.DateTimeField(auto_now_add=True)),
                ('m_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.operation')),
            ],
        ),
        migrations.CreateModel(
            name='EntityRapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date_rapport', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('m_resultat_realise', models.TextField(blank=True, null=True)),
                ('m_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityHierachie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_sub_entity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_entity', to='ctn_bpf.entity')),
                ('m_sup_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sup', to='ctn_bpf.entity')),
            ],
            options={
                'ordering': ('m_sup_entity', 'm_sub_entity'),
            },
        ),
        migrations.CreateModel(
            name='EntityFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_field', models.CharField(blank=True, max_length=32, null=True)),
                ('m_file', models.FileField(blank=True, null=True, upload_to='')),
                ('m_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.entity')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='m_type_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.entitytype'),
        ),
        migrations.CreateModel(
            name='DSet_DElt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_value', models.CharField(blank=True, max_length=128, null=True)),
                ('m_dataelement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.dataelement')),
                ('m_dataset_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.datasetvalue')),
                ('m_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.structure')),
            ],
        ),
        migrations.AddField(
            model_name='datasetvalue',
            name='m_structures',
            field=models.ManyToManyField(null=True, to='ctn_bpf.structure'),
        ),
        migrations.AddField(
            model_name='datasetvalue',
            name='m_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.personnel'),
        ),
        migrations.CreateModel(
            name='DataSetEntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.dataset')),
                ('m_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.entitytype')),
            ],
        ),
        migrations.CreateModel(
            name='DataSetEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.dataset')),
                ('m_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.entity')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='m_indicateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.indicateur'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='m_indicateurs',
            field=models.ManyToManyField(null=True, related_name='indicateurs', to='ctn_bpf.indicateur'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='m_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='m_roles',
            field=models.ManyToManyField(null=True, to='ctn_bpf.role'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='m_structures',
            field=models.ManyToManyField(null=True, to='ctn_bpf.structure'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='m_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution'),
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('m_message', models.TextField(blank=True, null=True)),
                ('m_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_nom', models.CharField(blank=True, max_length=64, null=True)),
                ('m_fields', models.TextField(blank=True, default='', null=True)),
                ('m_type_fields', models.TextField(blank=True, default='', null=True)),
                ('m_fields_rapported', models.TextField(blank=True, default='', null=True)),
                ('m_type_fields_rapp', models.TextField(blank=True, default='', null=True)),
                ('m_fields_calculate', models.TextField(blank=True, default='', null=True)),
                ('m_fields_fonction_calculate', models.TextField(blank=True, default='', null=True)),
                ('m_enum_values', models.TextField(blank=True, default='', null=True)),
                ('m_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
            ],
        ),
        migrations.CreateModel(
            name='TacheRepartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_personnels', models.ManyToManyField(blank=True, to='ctn_bpf.personnel')),
                ('m_roles', models.ManyToManyField(blank=True, to='ctn_bpf.role')),
                ('m_tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.tache')),
            ],
        ),
        migrations.CreateModel(
            name='TachePlannify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_planify', models.TextField(blank=True, null=True)),
                ('m_value', models.CharField(blank=True, max_length=256, null=True)),
                ('m_periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.periode')),
                ('m_tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.tache')),
            ],
        ),
        migrations.CreateModel(
            name='TachePeriode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_chronogramme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.periode')),
                ('m_tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.tache')),
            ],
        ),
        migrations.CreateModel(
            name='TacheAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_values1', models.TextField()),
                ('m_values2', models.TextField()),
                ('m_tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.tache')),
            ],
        ),
        migrations.AddField(
            model_name='tache',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.structure'),
        ),
        migrations.AddField(
            model_name='tache',
            name='structures',
            field=models.ManyToManyField(blank=True, to='ctn_bpf.structurerole'),
        ),
        migrations.AddField(
            model_name='operation',
            name='tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.tache'),
        ),
    ]
