# Generated by Django 4.2.1 on 2023-10-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0002_operation_date_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicraci',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='operationconsulted',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
