# Generated by Django 4.2.1 on 2023-10-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0004_alter_dataelement_m_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelement',
            name='m_name',
            field=models.CharField(blank=True, default='255', max_length=255, null=True),
        ),
    ]
