# Generated by Django 4.2.1 on 2023-10-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0005_alter_dataelement_m_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdetails',
            name='m_institution_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctn_bpf.institution'),
        ),
    ]
