# Generated by Django 4.2.1 on 2023-11-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0006_operationdetails_m_institution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicateur',
            name='m_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
