# Generated by Django 4.2.1 on 2023-11-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0007_alter_indicateur_m_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdetails',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
